import { test, expect } from "@playwright/test"
import { PrismaClient } from "@prisma/client"
import bcrypt from "bcryptjs"
import * as XLSX from "xlsx"

const url = process.env.E2E_DATABASE_URL ?? "postgresql://postgres:postgres@127.0.0.1:5432/tulemuste_haldus?schema=e2e"
const parsed = new URL(url)
if (!["localhost", "127.0.0.1", "::1"].includes(parsed.hostname) || parsed.searchParams.get("schema") !== "e2e") throw new Error("Requires isolated local e2e schema")
const db = new PrismaClient({ datasources: { db: { url } } })
test.afterAll(() => db.$disconnect())

test("organizer defines distances; scoped judge sets references and enters guesses; errors, scoring and export agree", async ({ page, request, browser }) => {
  test.setTimeout(90000)
  const password = "estimation-test"
  const user = await db.user.create({ data: { email: `estimate-${Date.now()}@example.com`, name: "Korraldaja", role: "ADMIN", passwordHash: await bcrypt.hash(password, 10) } })
  const competition = await db.competition.create({ data: { name: "Kauguste hindamine", createdById: user.id, organizerId: user.id, scoringMode: "PLUS", isPublic: true } })
  const team = await db.team.create({ data: { competitionId: competition.id, code: "1", name: "Pakkujad" } })
  await page.goto("/login")
  await page.getByPlaceholder("admin@example.com").fill(user.email)
  await page.locator('input[type="password"]').fill(password)
  await page.getByRole("button", { name: "Logi sisse" }).click()
  await page.waitForURL("**/dashboard")
  await Promise.all([page.waitForResponse(r => r.url().endsWith(`/api/competitions/${competition.id}`)), page.goto(`/dashboard/competitions/${competition.id}/elements/new`)])
  await expect(page.getByRole("button", { name: /Kasuta NATO/ })).toHaveCount(0)
  await page.getByPlaceholder("KP 1 Politsei").fill("Vahemaade määramine")
  await page.getByPlaceholder("1", { exact: true }).fill("S1")
  await page.locator('input[name="calcType"][value="ABSOLUTE_POINTS"]').check()
  await expect(page.locator('select').filter({ has: page.locator('option[value="ESTIMATION"]') }).first().locator('option')).toHaveText(["Arv", "Aeg (h:mm:ss)", "Aeg (kestvus)", "Aja hindamine vahemikena", "Valik punktidega", "Väärtuste hindamine veaprotsendi järgi", "Tekst", "Arvutatud"])
  await page.locator('select').filter({ has: page.locator('option[value="ESTIMATION"]') }).first().selectOption("ESTIMATION")
  await page.locator('input[value="aeg"]').fill("kaugused")
  await page.locator('input[value="Aeg"]').fill("Kaugused")
  await page.getByRole("button", { name: "+ Lisa väärtus", exact: true }).click()
  await page.getByRole("button", { name: "+ Lisa väärtus", exact: true }).click()
  await page.getByLabel("Rea 1 mõõtühik").fill("cm")
  await page.getByLabel("Veasumma mõõtühik").fill("cm")
  await expect(page.getByLabel("Rea 2 mõõtühik")).toHaveValue("m")
  await page.getByLabel("Veasumma mõõtühik").fill("m")
  await page.setViewportSize({ width: 390, height: 844 })
  await page.getByLabel("Rea 1 mõõtühik").scrollIntoViewIfNeeded()
  await page.screenshot({ path: "/tmp/estimation-units-editor-mobile.png" })
  await page.setViewportSize({ width: 1280, height: 800 })
  await expect(page.getByLabel("Veaprotsendi piir 1")).toHaveValue("5")
  await page.getByRole("button", { name: "Salvesta element", exact: true }).click()
  await page.waitForURL(`**/dashboard/competitions/${competition.id}`)
  const element = await db.scoringElement.findFirstOrThrow({ where: { competitionId: competition.id }, include: { fields: true } })
  const field = element.fields.find(f => f.type === "ESTIMATION")!
  const config = JSON.parse(field.meta!).estimation
  expect(config.targets.map((t: { correct: number | null }) => t.correct)).toEqual([null, null])
  const referenceEndpoint = `/api/elements/${element.id}/estimation-reference`
  const targetIds = config.targets.map((t: { id: string }) => t.id)
  const correct = { [targetIds[0]]: 100, [targetIds[1]]: 200 }
  expect((await request.patch(referenceEndpoint, { data: { fieldId: field.id, correct } })).status()).toBe(401)
  const other = await db.scoringElement.create({ data: { competitionId: competition.id, name: "Teine", code: "S2", order: 2 } })
  const wrongToken = await db.accessToken.create({ data: { competitionId: competition.id, elementId: other.id, type: "JUDGE", name: "Teise elemendi kohtunik" } })
  expect((await request.patch(referenceEndpoint, { headers: { "x-access-token": wrongToken.token }, data: { fieldId: field.id, correct } })).status()).toBe(403)
  const token = await db.accessToken.create({ data: { competitionId: competition.id, elementId: element.id, type: "JUDGE", name: "Kohtunik" } })
  const judgeContext = await browser.newContext({ baseURL: "http://127.0.0.1:3100", viewport: { width: 390, height: 844 } })
  const judge = await judgeContext.newPage()
  await judge.goto(`/judge/${token.token}`)
  await judge.getByText("Õiged väärtused: Kaugused", { exact: true }).click()
  await judge.getByLabel("Õige väärtus: Väärtus 1", { exact: true }).fill("100")
  await judge.getByLabel("Õige väärtus: Väärtus 2", { exact: true }).fill("200")
  await judge.getByRole("button", { name: "Salvesta õiged väärtused", exact: true }).click()
  await expect(judge.getByRole("status")).toContainText("Õiged väärtused salvestatud")
  await judge.getByRole("button", { name: /Pakkujad/ }).click()
  await judge.getByLabel("Kaugused: Väärtus 1", { exact: true }).fill("110")
  await judge.getByLabel("Kaugused: Väärtus 2", { exact: true }).fill("180")
  await expect(judge.getByText(/Kokku 4,0 p/)).toContainText("eksimus 20,1 m")
  await expect(judge.getByText(/Kokku 4,0 p/)).toContainText("protsendivigade summa 20,0%")
  await judge.screenshot({ path: "/tmp/estimation-judge-mobile.png", fullPage: true })
  await judge.getByRole("button", { name: "✓ Salvesta tulemus" }).click()
  await expect(judge.getByRole("button", { name: /Pakkujad/ })).toContainText("Sisestatud")
  expect((await db.computedScore.findFirstOrThrow({ where: { elementId: element.id, teamId: team.id } })).penaltyPoints).toBe(4)
  // A reference correction updates all stored results without changing the original guesses.
  await judge.getByLabel("Õige väärtus: Väärtus 1", { exact: true }).fill("110")
  await judge.getByRole("button", { name: "Salvesta õiged väärtused", exact: true }).click()
  await expect.poll(async () => (await db.computedScore.findFirstOrThrow({ where: { elementId: element.id, teamId: team.id } })).penaltyPoints).toBe(5)
  const saved = JSON.parse((await db.result.findFirstOrThrow({ where: { elementId: element.id, teamId: team.id } })).values)
  expect(JSON.parse(saved.kaugused)).toEqual({ [targetIds[0]]: "110", [targetIds[1]]: "180" })
  await judgeContext.close()
  const exported = await page.request.get(`/api/competitions/${competition.id}/elements/${element.id}/export?format=xlsx`)
  const book = XLSX.read(await exported.body(), { type: "buffer" })
  const csv = XLSX.utils.sheet_to_csv(book.Sheets[book.SheetNames[0]])
  expect(csv).toContain("Kaugused (Väärtus 1) [cm]")
  expect(csv).toContain("Kaugused: eksimus (m)")
  expect(csv).toContain("110,180,5,20,10")
  const response = await request.post(`/api/elements/${element.id}/results`, { headers: { "x-access-token": token.token }, data: { teamId: team.id, values: { kaugused: JSON.stringify({ [targetIds[0]]: -1, [targetIds[1]]: 180 }) } } })
  expect(response.status()).toBe(422)
})
