import { test, expect } from "@playwright/test"
import { PrismaClient } from "@prisma/client"
import bcrypt from "bcryptjs"

const url = process.env.E2E_DATABASE_URL ?? "postgresql://postgres:postgres@127.0.0.1:5432/tulemuste_haldus?schema=e2e"
const parsed = new URL(url)
if (!["localhost", "127.0.0.1", "::1"].includes(parsed.hostname) || parsed.searchParams.get("schema") !== "e2e") throw new Error("Requires isolated local e2e schema")
const db = new PrismaClient({ datasources: { db: { url } } })
test.afterAll(() => db.$disconnect())

test("configure point fields, enter judge results, preserve time and break only element ties", async ({ page }) => {
  test.setTimeout(90000)
  const password = "point-fields-test"
  const user = await db.user.create({ data: { email: `point-fields-${Date.now()}@example.com`, name: "Korraldaja", role: "ADMIN", passwordHash: await bcrypt.hash(password, 10) } })
  const competition = await db.competition.create({ data: { name: "Ajapunktid", createdById: user.id, organizerId: user.id, scoringMode: "PLUS", isPublic: true } })
  const slow = await db.team.create({ data: { competitionId: competition.id, code: "1", name: "Aeglasem", class: "A" } })
  const fast = await db.team.create({ data: { competitionId: competition.id, code: "2", name: "Kiirem", class: "A" } })
  await page.goto("/login")
  await page.getByPlaceholder("admin@example.com").fill(user.email)
  await page.locator('input[type="password"]').fill(password)
  await page.getByRole("button", { name: "Logi sisse" }).click()
  await page.waitForURL("**/dashboard")
  await page.goto(`/dashboard/competitions/${competition.id}/elements/new`)
  await page.getByPlaceholder("KP 1 Politsei").fill("NATO ülesanne")
  await page.getByPlaceholder("1", { exact: true }).fill("S1")
  await page.getByRole("button", { name: "Kasuta NATO ülesande näidist (40 p)" }).click()
  await expect(page.getByLabel("Valiku nimetus")).toHaveCount(5)
  await expect(page.getByLabel("Ajavahemiku lõpp")).toHaveCount(15)
  await page.setViewportSize({ width: 390, height: 844 })
  await page.getByLabel("Ajavahemiku lõpp").first().scrollIntoViewIfNeeded()
  await page.screenshot({ path: "/tmp/tulemuste-point-fields-editor-mobile.png" })
  await page.setViewportSize({ width: 1280, height: 800 })
  await page.getByRole("button", { name: "Salvesta element", exact: true }).click()
  await page.waitForURL(`**/dashboard/competitions/${competition.id}`)
  const element = await db.scoringElement.findFirstOrThrow({ where: { competitionId: competition.id }, include: { fields: true } })
  const endpoint = `/api/elements/${element.id}/results`
  expect((await page.request.post(endpoint, { data: { teamId: slow.id, values: { nato: "forged", sedelid: "9", lahendus: "yes", aeg: "4:15" } } })).status()).toBe(422)
  const token = await db.accessToken.create({ data: { competitionId: competition.id, elementId: element.id, type: "JUDGE", name: "Kohtunik" } })
  await page.goto(`/judge/${token.token}`)
  await page.getByRole("button", { name: /Aeglasem/ }).click()
  await page.getByLabel("NATO tähestiku kasutamine", { exact: true }).selectOption("yes")
  await page.getByLabel("Lahendussõna leidmine", { exact: true }).selectOption("yes")
  await page.locator('form input[type="number"]').fill("9")
  await page.getByLabel("Aeg", { exact: true }).fill("415")
  await page.getByRole("button", { name: "✓ Salvesta tulemus" }).click()
  await expect(page.getByRole("button", { name: /Aeglasem/ })).toContainText("Sisestatud")
  expect((await db.computedScore.findFirstOrThrow({ where: { elementId: element.id, teamId: slow.id } })).penaltyPoints).toBe(40)
  expect((await page.request.post(endpoint, { data: { teamId: fast.id, values: { nato: "yes", sedelid: "9", lahendus: "yes", aeg: "4:01" } } })).ok()).toBe(true)
  await page.goto(`/dashboard/competitions/${competition.id}/elements/${element.id}`)
  const table = page.locator("table").filter({ has: page.getByRole("columnheader", { name: "NATO tähestiku kasutamine", exact: true }) })
  await expect(table.locator("tbody tr").first()).toContainText("Kiirem")
  await expect(table.locator("tbody tr").first()).toContainText("4:01 (15 p)")
  await expect(table.locator("tbody tr").first()).toContainText("Kasutab (2 p)")
  const leaderboard = await (await page.request.get(`/api/competitions/${competition.id}/leaderboard`)).json()
  expect(leaderboard.leaderboard.map((r: { rank: number }) => r.rank)).toEqual([1, 1])
  await page.screenshot({ path: "/tmp/tulemuste-point-fields-results.png", fullPage: true })
  const csv = await (await page.request.get(`/api/competitions/${competition.id}/elements/${element.id}/export?format=csv`)).text()
  expect(csv).toContain("Kasutab (2 p)")
  expect(csv).toContain("4:01")
  await page.goto(`/public/${competition.id}/analysis`)
  await page.getByRole("button", { name: "KP võrdlus", exact: true }).click()
  const publicTable = page.locator("table").filter({ has: page.getByRole("columnheader", { name: "NATO tähestiku kasutamine", exact: true }) })
  await expect(publicTable.locator("tbody tr").first()).toContainText("Kiirem")
  await expect(publicTable.locator("tbody tr").first()).toContainText("4:01 (15 p)")
  await expect(publicTable.locator("tbody tr").first().getByRole("cell").first()).toHaveText("1")
  await expect(publicTable.locator("tbody tr").nth(1).getByRole("cell").first()).toHaveText("2")
  // Edit and reload preserve the full configuration and update existing scores.
  await page.goto(`/dashboard/competitions/${competition.id}/elements/${element.id}/edit`)
  await expect(page.getByLabel("Valiku nimetus")).toHaveCount(5)
  await expect(page.getByLabel("Ajavahemiku lõpp").first()).toHaveValue("4:15")
  await page.getByLabel("Valiku punktid").first().fill("3")
  await page.getByRole("button", { name: /Salvesta/ }).last().click()
  await page.waitForURL(`**/elements/${element.id}`)
  expect((await db.computedScore.findFirstOrThrow({ where: { elementId: element.id, teamId: slow.id } })).penaltyPoints).toBe(41)
  // Regression: time must also resolve the rank used to allocate penalty points.
  await db.competition.update({ where: { id: competition.id }, data: { scoringMode: "PENALTY" } })
  expect((await page.request.patch(`/api/elements/${element.id}`, { data: { maxValue: 40, calcMethod: { type: "RELATIVE_RANKING", params: { higherIsBetter: true, minPoints: 0 } } } })).ok()).toBe(true)
  const third = await db.team.create({ data: { competitionId: competition.id, code: "3", name: "Kolmas", class: "A" } })
  expect((await page.request.post(endpoint, { data: { teamId: third.id, values: { nato: "partly", sedelid: "8", lahendus: "no", aeg: "4:00" } } })).ok()).toBe(true)
  const penaltyScores = await db.computedScore.findMany({ where: { elementId: element.id } })
  expect(penaltyScores.find(s => s.teamId === fast.id)?.penaltyPoints).toBe(0)
  expect(penaltyScores.find(s => s.teamId === slow.id)?.penaltyPoints).toBe(20)
  expect(penaltyScores.find(s => s.teamId === third.id)?.penaltyPoints).toBe(40)
  await page.goto(`/dashboard/competitions/${competition.id}/elements/${element.id}`)
  await expect(table.locator("tbody tr").nth(1)).toContainText("20.00")

})
